### PR TITLE
Add needed env variables to github action for k8s deployment

### PR DESCRIPTION
**Pull request by JulianRoesner**
# Short Description
The deployment step for Kubernetes needs additional environment variables (namespace and the kubeconfig). This adds those env variables to the deployment steps

# Feedback
- Did I forget any env variables?
- Anything else?

# How to review this Pull Request
[Link to Confluence](https://digitalservice4germany.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

### CODE REVIEW

**Review by VictorDelCampo — CHANGES_REQUESTED** [review]
Looks good but we still have to clarify the topic with the network docker host!

**Comment by JulianRoesner** [comment]
> Looks good but we still have to clarify the topic with the network docker host!

Let's talk about it.

**Comment by JulianRoesner** [comment]
@VictorDelCampo We won't need to adapt the network docker host because this is only relevant for local development, correct?

**Comment by VictorDelCampo** [comment]
> @VictorDelCampo We won't need to adapt the network docker host because this is only relevant for local development, correct?

Correct!

**Review by VictorDelCampo — APPROVED** [review]

**Pull request merged**
